var createPnnxModule=(()=>{var _scriptName=globalThis.document?.currentScript?.src;return async function(moduleArg={}){var moduleRtn;var e=moduleArg,aa=!!globalThis.window,ba=!!globalThis.WorkerGlobalScope,ca=[],da="./this.program";ba&&(_scriptName=self.location.href);var fa="",ha,ia;if(aa||ba){try{fa=(new URL(".",_scriptName)).href}catch{}ba&&(ia=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});ha=async a=>{a=await fetch(a,{credentials:"same-origin"});if(a.ok)return a.arrayBuffer();throw Error(a.status+" : "+a.url);}}
var ja=console.log.bind(console),k=console.error.bind(console),m,ka=!1,q,la,ma,u,v,na,w,x,oa,A,C,pa=!1;function qa(){var a=ra.buffer;u=new Int8Array(a);na=new Int16Array(a);v=new Uint8Array(a);new Uint16Array(a);w=new Int32Array(a);x=new Uint32Array(a);new Float32Array(a);oa=new Float64Array(a);A=new BigInt64Array(a);C=new BigUint64Array(a)}function F(a){e.onAbort?.(a);a="Aborted("+a+")";k(a);ka=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");ma?.(a);throw a;}var sa;
async function ta(a){if(!m)try{var b=await ha(a);return new Uint8Array(b)}catch{}if(a==sa&&m)a=new Uint8Array(m);else if(ia)a=ia(a);else throw"both async and sync fetching of the wasm failed";return a}async function ua(a,b){try{var c=await ta(a);return await WebAssembly.instantiate(c,b)}catch(d){k(`failed to asynchronously prepare wasm: ${d}`),F(d)}}
async function va(a){var b=sa;if(!m)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){k(`wasm streaming compile failed: ${d}`),k("falling back to ArrayBuffer instantiation")}return ua(b,a)}class wa{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var xa=a=>{for(;0<a.length;)a.shift()(e)},ya=[],za=[],Aa=()=>{var a=e.preRun.shift();za.push(a)},Ba=!0,G=a=>-9007199254740992>a||9007199254740992<a?NaN:Number(a),Ca=new TextDecoder,Da=(a,b)=>{for(var c=b+void 0;a[b]&&!(b>=c);)++b;return b},H=a=>a?Ca.decode(v.subarray(a,Da(v,a))):"";class Ea{constructor(a){this.wa=a-48}Ea(a,b){C[(this.wa+32)/8]=BigInt(0);C[(this.wa+8)/8]=BigInt(a);C[(this.wa+16)/8]=BigInt(b)}}
var Fa=0,Ga=0,J=()=>{var a=Number(C[I/8]);I+=8;return a},Ha=()=>{var a=w[+I/4];I+=4;return a},Ia=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var f=a[d];"."===f?a.splice(d,1):".."===f?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},K=a=>{var b="/"===a.charAt(0),c="/"===a.slice(-1);(a=Ia(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},Ja=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);
a=b[0];b=b[1];if(!a&&!b)return".";b&&=b.slice(0,-1);return a+b},L=a=>a&&a.match(/([^\/]+|\/)\/*$/)[1],Ka=(a,b)=>K(a+"/"+b),La=()=>a=>crypto.getRandomValues(a),Ma=a=>{(Ma=La())(a)},Na=(...a)=>{for(var b="",c=!1,d=a.length-1;-1<=d&&!c;d--){c=0<=d?a[d]:M.Ba();if("string"!=typeof c)throw new TypeError("Arguments to path.resolve must be strings");if(!c)return"";b=c+"/"+b;c="/"===c.charAt(0)}b=Ia(b.split("/").filter(f=>!!f),!c).join("/");return(c?"/":"")+b||"."},Oa=(a,b)=>{function c(h){for(var n=0;n<h.length&&
""===h[n];n++);for(var r=h.length-1;0<=r&&""===h[r];r--);return n>r?[]:h.slice(n,r-n+1)}a=Na(a).slice(1);b=Na(b).slice(1);a=c(a.split("/"));b=c(b.split("/"));for(var d=Math.min(a.length,b.length),f=d,g=0;g<d;g++)if(a[g]!==b[g]){f=g;break}d=[];for(g=f;g<a.length;g++)d.push("..");d=d.concat(b.slice(f));return d.join("/")},Pa=a=>{var b=Da(a,0);return Ca.decode(a.buffer?a.subarray(0,b):new Uint8Array(a.slice(0,b)))},Qa=[],Ra=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?
b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},N=(a,b,c,d)=>{if(!(0<d))return 0;var f=c;d=c+d-1;for(var g=0;g<a.length;++g){var h=a.codePointAt(g);if(127>=h){if(c>=d)break;b[c++]=h}else if(2047>=h){if(c+1>=d)break;b[c++]=192|h>>6;b[c++]=128|h&63}else if(65535>=h){if(c+2>=d)break;b[c++]=224|h>>12;b[c++]=128|h>>6&63;b[c++]=128|h&63}else{if(c+3>=d)break;b[c++]=240|h>>18;b[c++]=128|h>>12&63;b[c++]=128|h>>6&63;b[c++]=128|h&63;g++}}b[c]=0;return c-f},Sa=a=>{var b=Array(Ra(a)+1);a=N(a,b,0,b.length);b.length=
a;return b},Ta=[];function Ua(a,b){Ta[a]={input:[],output:[],ka:b};Va(a,Wa)}
var Wa={open(a){var b=Ta[a.node.ya];if(!b)throw new M.R(43);a.V=b;a.seekable=!1},close(a){a.V.ka.Da(a.V)},Da(a){a.V.ka.Da(a.V)},read(a,b,c,d){if(!a.V||!a.V.ka.$a)throw new M.R(60);for(var f=0,g=0;g<d;g++){try{var h=a.V.ka.$a(a.V)}catch(n){throw new M.R(29);}if(void 0===h&&0===f)throw new M.R(6);if(null===h||void 0===h)break;f++;b[c+g]=h}f&&(a.node.ha=Date.now());return f},write(a,b,c,d){if(!a.V||!a.V.ka.Pa)throw new M.R(60);try{for(var f=0;f<d;f++)a.V.ka.Pa(a.V,b[c+f])}catch(g){throw new M.R(29);
}d&&(a.node.aa=a.node.Z=Date.now());return f}},Xa={$a(){a:{if(!Qa.length){var a=null;globalThis.window?.prompt&&(a=window.prompt("Input: "),null!==a&&(a+="\n"));if(!a){a=null;break a}Qa=Sa(a)}a=Qa.shift()}return a},Pa(a,b){null===b||10===b?(ja(Pa(a.output)),a.output=[]):0!=b&&a.output.push(b)},Da(a){0<a.output?.length&&(ja(Pa(a.output)),a.output=[])},tb(){return{Hb:25856,Jb:5,Gb:191,Ib:35387,Fb:[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},ub(){return 0},vb(){return[24,
80]}},Ya={Pa(a,b){null===b||10===b?(k(Pa(a.output)),a.output=[]):0!=b&&a.output.push(b)},Da(a){0<a.output?.length&&(k(Pa(a.output)),a.output=[])}},$a=a=>{a=65536*Math.ceil(a/65536);var b=Za(65536,a);b&&v.fill(0,b,b+a);return b},O={fa:null,X(){return O.createNode(null,"/",16895,0)},createNode(a,b,c,d){var f;(f=24576===(c&61440))||(f=4096===(c&61440));if(f)throw new M.R(63);O.fa||(O.fa={dir:{node:{ca:O.S.ca,ea:O.S.ea,pa:O.S.pa,ia:O.S.ia,Aa:O.S.Aa,ua:O.S.ua,ta:O.S.ta,za:O.S.za,oa:O.S.oa},stream:{$:O.T.$}},
file:{node:{ca:O.S.ca,ea:O.S.ea},stream:{$:O.T.$,read:O.T.read,write:O.T.write,ra:O.T.ra,va:O.T.va}},link:{node:{ca:O.S.ca,ea:O.S.ea,na:O.S.na},stream:{}},Wa:{node:{ca:O.S.ca,ea:O.S.ea},stream:M.lb}});c=M.createNode(a,b,c,d);P(c.mode)?(c.S=O.fa.dir.node,c.T=O.fa.dir.stream,c.U={}):M.isFile(c.mode)?(c.S=O.fa.file.node,c.T=O.fa.file.stream,c.Y=0,c.U=null):40960===(c.mode&61440)?(c.S=O.fa.link.node,c.T=O.fa.link.stream):8192===(c.mode&61440)&&(c.S=O.fa.Wa.node,c.T=O.fa.Wa.stream);c.ha=c.aa=c.Z=Date.now();
a&&(a.U[b]=c,a.ha=a.aa=a.Z=c.ha);return c},Ub(a){return a.U?a.U.subarray?a.U.subarray(0,a.Y):new Uint8Array(a.U):new Uint8Array(0)},S:{ca(a){var b={};b.mb=8192===(a.mode&61440)?a.id:1;b.sb=a.id;b.mode=a.mode;b.yb=1;b.uid=0;b.rb=0;b.ya=a.ya;P(a.mode)?b.size=4096:M.isFile(a.mode)?b.size=a.Y:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.ha=new Date(a.ha);b.aa=new Date(a.aa);b.Z=new Date(a.Z);b.kb=4096;b.Va=Math.ceil(b.size/b.kb);return b},ea(a,b){for(var c of["mode","atime","mtime","ctime"])null!=
b[c]&&(a[c]=b[c]);void 0!==b.size&&(b=b.size,a.Y!=b&&(0==b?(a.U=null,a.Y=0):(c=a.U,a.U=new Uint8Array(b),c&&a.U.set(c.subarray(0,Math.min(b,a.Y))),a.Y=b)))},pa(){O.Ia||(O.Ia=new M.R(44),O.Ia.stack="<generic error, no stack>");throw O.Ia;},ia(a,b,c,d){return O.createNode(a,b,c,d)},Aa(a,b,c){try{var d=Q(b,c)}catch(g){}if(d){if(P(a.mode))for(var f in d.U)throw new M.R(55);ab(d)}delete a.parent.U[a.name];b.U[c]=a;a.name=c;b.Z=b.aa=a.parent.Z=a.parent.aa=Date.now()},ua(a,b){delete a.U[b];a.Z=a.aa=Date.now()},
ta(a,b){var c=Q(a,b),d;for(d in c.U)throw new M.R(55);delete a.U[b];a.Z=a.aa=Date.now()},za(a){return[".","..",...Object.keys(a.U)]},oa(a,b,c){a=O.createNode(a,b,41471,0);a.link=c;return a},na(a){if(40960!==(a.mode&61440))throw new M.R(28);return a.link}},T:{read(a,b,c,d,f){var g=a.node.U;if(f>=a.node.Y)return 0;a=Math.min(a.node.Y-f,d);if(8<a&&g.subarray)b.set(g.subarray(f,f+a),c);else for(d=0;d<a;d++)b[c+d]=g[f+d];return a},write(a,b,c,d,f,g){b.buffer===u.buffer&&(g=!1);if(!d)return 0;a=a.node;
a.aa=a.Z=Date.now();if(b.subarray&&(!a.U||a.U.subarray)){if(g)return a.U=b.subarray(c,c+d),a.Y=d;if(0===a.Y&&0===f)return a.U=b.slice(c,c+d),a.Y=d;if(f+d<=a.Y)return a.U.set(b.subarray(c,c+d),f),d}g=f+d;var h=a.U?a.U.length:0;h>=g||(g=Math.max(g,h*(1048576>h?2:1.125)>>>0),0!=h&&(g=Math.max(g,256)),h=a.U,a.U=new Uint8Array(g),0<a.Y&&a.U.set(h.subarray(0,a.Y),0));if(a.U.subarray&&b.subarray)a.U.set(b.subarray(c,c+d),f);else for(g=0;g<d;g++)a.U[f+g]=b[c+g];a.Y=Math.max(a.Y,f+d);return d},$(a,b,c){1===
c?b+=a.position:2===c&&M.isFile(a.node.mode)&&(b+=a.node.Y);if(0>b)throw new M.R(28);return b},ra(a,b,c,d,f){if(!M.isFile(a.node.mode))throw new M.R(43);a=a.node.U;if(f&2||!a||a.buffer!==u.buffer){d=!0;f=$a(b);if(!f)throw new M.R(48);if(a){if(0<c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);u.set(a,f)}}else d=!1,f=a.byteOffset;return{wa:f,Ua:d}},va(a,b,c,d){O.T.write(a,b,0,d,c,!1);return 0}}},bb=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},cb=async a=>{a=
await ha(a);return new Uint8Array(a)},R=0,db=null,eb=()=>{R--;e.monitorRunDependencies?.(R);if(0==R&&db){var a=db;db=null;a()}},fb=()=>{R++;e.monitorRunDependencies?.(R)},gb=[],hb=async(a,b)=>{"undefined"!=typeof Browser&&Browser.Ea();for(var c of gb)if(c.canHandle(b))return c.handle(a,b);return a},jb=async(a,b,c,d,f,g,h,n)=>{var r=b?Na(K(a+"/"+b)):a,p=`cp ${r}`;fb(p);try{var l=c;"string"==typeof c&&(l=await cb(c));l=await hb(l,r);n?.();g||ib(a,b,l,d,f,h)}finally{eb(p)}};
function Va(a,b){M.Ya[a]={T:b}}function P(a){return 16384===(a&61440)}function Q(a,b){var c=P(a.mode)?(c=S(a,"x"))?c:a.S.pa?0:2:54;if(c)throw new M.R(c);for(c=M.ja[kb(a.id,b)];c;c=c.sa){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return M.pa(a,b)}function ab(a){var b=kb(a.parent.id,a.name);if(M.ja[b]===a)M.ja[b]=a.sa;else for(b=M.ja[b];b;){if(b.sa===a){b.sa=a.sa;break}b=b.sa}}
function ib(a,b,c,d,f,g){var h=b;a&&(a="string"==typeof a?a:T(a),h=b?K(a+"/"+b):a);a=bb(d,f);h=M.create(h,a);if(c){if("string"==typeof c){b=Array(c.length);d=0;for(f=c.length;d<f;++d)b[d]=c.charCodeAt(d);c=b}lb(h,a|146);b=M.open(h,577);M.write(b,c,0,c.length,0,g);M.close(b);lb(h,a)}}
function U(a,b={}){if(!a)throw new M.R(44);b.Ca??(b.Ca=!0);"/"===a.charAt(0)||(a=M.Ba()+"/"+a);var c=0;a:for(;40>c;c++){a=a.split("/").filter(n=>!!n);for(var d=M.root,f="/",g=0;g<a.length;g++){var h=g===a.length-1;if(h&&b.parent)break;if("."!==a[g])if(".."===a[g])if(f=Ja(f),M.Ma(d)){a=f+"/"+a.slice(g+1).join("/");c--;continue a}else d=d.parent;else{f=K(f+"/"+a[g]);try{d=Q(d,a[g])}catch(n){if(44===n?.W&&h&&b.zb)return{path:f};throw n;}!d.da||h&&!b.Ca||(d=d.da.root);if(40960===(d.mode&61440)&&(!h||
b.ba)){if(!d.S.na)throw new M.R(52);d=d.S.na(d);"/"===d.charAt(0)||(d=Ja(f)+"/"+d);a=d+"/"+a.slice(g+1).join("/");continue a}}}return{path:f,node:d}}throw new M.R(32);}function T(a){for(var b;;){if(M.Ma(a))return a=a.X.bb,b?"/"!==a[a.length-1]?`${a}/${b}`:a+b:a;b=b?`${a.name}/${b}`:a.name;a=a.parent}}function kb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%M.ja.length}function mb(a){var b=kb(a.parent.id,a.name);a.sa=M.ja[b];M.ja[b]=a}
function nb(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function S(a,b){if(M.ab)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0}function ob(a,b){if(!P(a.mode))return 54;try{return Q(a,b),20}catch(c){}return S(a,"wx")}
function pb(a,b,c){try{var d=Q(a,b)}catch(f){return f.W}if(a=S(a,"wx"))return a;if(c){if(!P(d.mode))return 54;if(M.Ma(d)||T(d)===M.Ba())return 10}else if(P(d.mode))return 31;return 0}function qb(a,b){if(!a)throw new M.R(b);return a}function V(a){a=M.qb(a);if(!a)throw new M.R(8);return a}function rb(a,b=-1){a=Object.assign(new M.hb,a);if(-1==b)a:{for(b=0;b<=M.ib;b++)if(!M.streams[b])break a;throw new M.R(33);}a.ma=b;return M.streams[b]=a}function sb(a,b=-1){a=rb(a,b);a.T?.Nb?.(a);return a}
function tb(a,b,c){var d=a?.T.ea;a=d?a:b;d??=b.S.ea;qb(d,63);d(a,c)}function ub(a){var b=[];for(a=[a];a.length;){var c=a.pop();b.push(c);a.push(...c.xa)}return b}function vb(a){var b={Eb:4096,Sb:4096,Va:1E6,Db:5E5,Cb:5E5,files:M.Oa,Qb:M.Oa-1,Tb:42,flags:2,$b:255};a.S.eb&&Object.assign(b,a.S.eb(a.X.Ab.root));return b}function Y(a,b=511){return M.ia(a,b&1023|16384,0)}function wb(a,b,c){"undefined"==typeof c&&(c=b,b=438);return M.ia(a,b|8192,c)}
function xb(a){var b=V(a);a=b.node;var c=b.T.ca;b=c?b:a;c??=a.S.ca;qb(c,63);return c(b)}function yb(a,b,c,d){tb(a,b,{mode:c&4095|b.mode&-4096,Z:Date.now(),Za:d})}function lb(a,b,c){a="string"==typeof a?U(a,{ba:!c}).node:a;yb(null,a,b,c)}function zb(a,b,c){if(P(b.mode))throw new M.R(31);if(!M.isFile(b.mode))throw new M.R(28);var d=S(b,"w");if(d)throw new M.R(d);tb(a,b,{size:c,timestamp:Date.now()})}function Ab(a,b){a=V(a);if(0>b||0===(a.flags&2097155))throw new M.R(28);zb(a,a.node,b)}
function Bb(a,b){a="string"==typeof a?a:T(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=K(a+"/"+c);try{Y(d)}catch(f){if(20!=f.W)throw f;}a=d}}return d}function Cb(a,b,c,d){a="string"==typeof a?a:T(a);b=K(a+"/"+b);return M.create(b,bb(c,d))}
function Db(a){if(!(a.wb||a.xb||a.link||a.U))if(globalThis.XMLHttpRequest)F("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");else try{a.U=ia(a.url)}catch(b){throw new M.R(29);}}
function Eb(a,b,c,d,f){function g(l,t,y,D,B){l=l.node.U;if(B>=l.length)return 0;D=Math.min(l.length-B,D);if(l.slice)for(var z=0;z<D;z++)t[y+z]=l[B+z];else for(z=0;z<D;z++)t[y+z]=l.get(B+z);return D}class h{Ha=!1;ga=[];Ga=void 0;Ra=0;Qa=0;get(l){if(!(l>this.length-1||0>l)){var t=l%this.Ta;return this.Ga(l/this.Ta|0)[t]}}jb(l){this.Ga=l}Sa(){var l=new XMLHttpRequest;l.open("HEAD",c,!1);l.send(null);200<=l.status&&300>l.status||304===l.status||F("Couldn't load "+c+". Status: "+l.status);var t=Number(l.getResponseHeader("Content-length")),
y,D=(y=l.getResponseHeader("Accept-Ranges"))&&"bytes"===y;l=(y=l.getResponseHeader("Content-Encoding"))&&"gzip"===y;var B=1048576;D||(B=t);var z=this;z.jb(W=>{var ea=W*B,X=(W+1)*B-1;X=Math.min(X,t-1);if("undefined"==typeof z.ga[W]){var Ub=z.ga;ea>X&&F("invalid range ("+ea+", "+X+") or no bytes requested!");X>t-1&&F("only "+t+" bytes available! programmer error!");var E=new XMLHttpRequest;E.open("GET",c,!1);t!==B&&E.setRequestHeader("Range","bytes="+ea+"-"+X);E.responseType="arraybuffer";E.overrideMimeType&&
E.overrideMimeType("text/plain; charset=x-user-defined");E.send(null);200<=E.status&&300>E.status||304===E.status||F("Couldn't load "+c+". Status: "+E.status);ea=void 0!==E.response?new Uint8Array(E.response||[]):Sa(E.responseText||"");Ub[W]=ea}"undefined"==typeof z.ga[W]&&F("doXHR failed!");return z.ga[W]});if(l||!t)B=t=1,B=t=this.Ga(0).length,ja("LazyFiles on gzip forces download of the whole file when length is accessed");this.Ra=t;this.Qa=B;this.Ha=!0}get length(){this.Ha||this.Sa();return this.Ra}get Ta(){this.Ha||
this.Sa();return this.Qa}}if(globalThis.XMLHttpRequest){ba||F("Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc");var n=new h;var r=void 0}else r=c,n=void 0;var p=Cb(a,b,d,f);n?p.U=n:r&&(p.U=null,p.url=r);Object.defineProperties(p,{Y:{get:function(){return this.U.length}}});a={};for(const [l,t]of Object.entries(p.T))a[l]=(...y)=>{Db(p);return t(...y)};a.read=(l,t,y,D,B)=>{Db(p);return g(l,t,y,D,B)};a.ra=(l,t,y)=>{Db(p);var D=$a(t);
if(!D)throw new M.R(48);g(l,u,D,t,y);return{wa:D,Ua:!0}};p.T=a;return p}
var M={root:null,xa:[],Ya:{},streams:[],Oa:1,ja:null,Xa:"/",Ka:!1,ab:!0,ob:null,Fa:0,cb:{},R:class{name="ErrnoError";constructor(a){this.W=a}},hb:class{ga={};node=null;get object(){return this.node}set object(a){this.node=a}get flags(){return this.ga.flags}set flags(a){this.ga.flags=a}get position(){return this.ga.position}set position(a){this.ga.position=a}},gb:class{S={};T={};da=null;constructor(a,b,c,d){a||=this;this.parent=a;this.X=a.X;this.id=M.Oa++;this.name=b;this.mode=c;this.ya=d;this.ha=
this.aa=this.Z=Date.now()}get read(){return 365===(this.mode&365)}set read(a){a?this.mode|=365:this.mode&=-366}get write(){return 146===(this.mode&146)}set write(a){a?this.mode|=146:this.mode&=-147}get xb(){return P(this.mode)}get wb(){return 8192===(this.mode&61440)}},createNode(a,b,c,d){a=new M.gb(a,b,c,d);mb(a);return a},Ma(a){return a===a.parent},isFile(a){return 32768===(a&61440)},Vb(a){return 49152===(a&49152)},ib:4096,qb:a=>M.streams[a],lb:{open(a){a.T=M.pb(a.node.ya).T;a.T.open?.(a)},$(){throw new M.R(70);
}},Na:a=>a>>8,Yb:a=>a&255,qa:(a,b)=>a<<8|b,pb:a=>M.Ya[a],fb(a,b){function c(n){M.Fa--;return b(n)}function d(n){if(n){if(!d.nb)return d.nb=!0,c(n)}else++g>=f.length&&c(null)}"function"==typeof a&&(b=a,a=!1);M.Fa++;1<M.Fa&&k(`warning: ${M.Fa} FS.syncfs operations in flight at once, probably just doing extra work`);var f=ub(M.root.X),g=0,h;for(h of f)h.type.fb?h.type.fb(h,a,d):d(null)},X(a,b,c){var d="/"===c;if(d&&M.root)throw new M.R(10);if(!d&&c){var f=U(c,{Ca:!1});c=f.path;f=f.node;if(f.da)throw new M.R(10);
if(!P(f.mode))throw new M.R(54);}b={type:a,Ab:b,bb:c,xa:[]};a=a.X(b);a.X=b;b.root=a;d?M.root=a:f&&(f.da=b,f.X&&f.X.xa.push(b));return a},fc(a){a=U(a,{Ca:!1});if(!a.node.da)throw new M.R(28);a=a.node;var b=a.da,c=ub(b);for([,f]of Object.entries(M.ja))for(;f;){var d=f.sa;c.includes(f.X)&&ab(f);var f=d}a.da=null;a.X.xa.splice(a.X.xa.indexOf(b),1)},pa(a,b){return a.S.pa(a,b)},ia(a,b,c){var d=U(a,{parent:!0}).node;a=L(a);if(!a)throw new M.R(28);if("."===a||".."===a)throw new M.R(20);var f=ob(d,a);if(f)throw new M.R(f);
if(!d.S.ia)throw new M.R(63);return d.S.ia(d,a,b,c)},eb(a){return vb(U(a,{ba:!0}).node)},dc(a){return vb(a.node)},create(a,b=438){return M.ia(a,b&4095|32768,0)},Zb(a,b){var c=a.split("/"),d="",f;for(f of c)if(f){if(d||"/"===a.charAt(0))d+="/";d+=f;try{Y(d,b)}catch(g){if(20!=g.W)throw g;}}},oa(a,b){if(!Na(a))throw new M.R(44);var c=U(b,{parent:!0}).node;if(!c)throw new M.R(44);b=L(b);var d=ob(c,b);if(d)throw new M.R(d);if(!c.S.oa)throw new M.R(63);return c.S.oa(c,b,a)},Aa(a,b){var c=Ja(a),d=Ja(b),
f=L(a),g=L(b);var h=U(a,{parent:!0});var n=h.node;h=U(b,{parent:!0});h=h.node;if(!n||!h)throw new M.R(44);if(n.X!==h.X)throw new M.R(75);var r=Q(n,f);a=Oa(a,d);if("."!==a.charAt(0))throw new M.R(28);a=Oa(b,c);if("."!==a.charAt(0))throw new M.R(55);try{var p=Q(h,g)}catch(l){}if(r!==p){b=P(r.mode);if(f=pb(n,f,b))throw new M.R(f);if(f=p?pb(h,g,b):ob(h,g))throw new M.R(f);if(!n.S.Aa)throw new M.R(63);if(r.da||p&&p.da)throw new M.R(10);if(h!==n&&(f=S(n,"w")))throw new M.R(f);ab(r);try{n.S.Aa(r,h,g),r.parent=
h}catch(l){throw l;}finally{mb(r)}}},ta(a){var b=U(a,{parent:!0}).node;a=L(a);var c=Q(b,a),d=pb(b,a,!0);if(d)throw new M.R(d);if(!b.S.ta)throw new M.R(63);if(c.da)throw new M.R(10);b.S.ta(b,a);ab(c)},za(a){a=U(a,{ba:!0}).node;return qb(a.S.za,54)(a)},ua(a){var b=U(a,{parent:!0}).node;if(!b)throw new M.R(44);a=L(a);var c=Q(b,a),d=pb(b,a,!1);if(d)throw new M.R(d);if(!b.S.ua)throw new M.R(63);if(c.da)throw new M.R(10);b.S.ua(b,a);ab(c)},na(a){a=U(a).node;if(!a)throw new M.R(44);if(!a.S.na)throw new M.R(28);
return a.S.na(a)},stat(a,b){a=U(a,{ba:!b}).node;return qb(a.S.ca,63)(a)},Wb(a,b){lb(a,b,!0)},Ob(a,b){a=V(a);yb(a,a.node,b,!1)},Xb(a){a="string"==typeof a?U(a,{ba:!1}).node:a;tb(null,a,{timestamp:Date.now(),Za:!0})},Pb(a){a=V(a);tb(a,a.node,{timestamp:Date.now(),Za:!1})},truncate(a,b){if(0>b)throw new M.R(28);a="string"==typeof a?U(a,{ba:!0}).node:a;zb(null,a,b)},hc(a,b,c){a=U(a,{ba:!0}).node;qb(a.S.ea,63)(a,{ha:b,aa:c})},open(a,b,c=438){if(""===a)throw new M.R(44);if("string"==typeof b){var d={r:0,
"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if("undefined"==typeof d)throw Error(`Unknown file open mode: ${b}`);b=d}c=b&64?c&4095|32768:0;if("object"==typeof a)d=a;else{var f=a.endsWith("/");a=U(a,{ba:!(b&131072),zb:!0});d=a.node;a=a.path}var g=!1;if(b&64)if(d){if(b&128)throw new M.R(20);}else{if(f)throw new M.R(31);d=M.ia(a,c|511,0);g=!0}if(!d)throw new M.R(44);8192===(d.mode&61440)&&(b&=-513);if(b&65536&&!P(d.mode))throw new M.R(54);if(!g&&(f=d?40960===(d.mode&61440)?32:P(d.mode)&&("r"!==nb(b)||
b&576)?31:S(d,nb(b)):44))throw new M.R(f);b&512&&!g&&M.truncate(d,0);b&=-131713;f=rb({node:d,path:T(d),flags:b,seekable:!0,position:0,T:d.T,Bb:[],error:!1});f.T.open&&f.T.open(f);g&&lb(d,c&511);!e.logReadFiles||b&1||a in M.cb||(M.cb[a]=1);return f},close(a){if(null===a.ma)throw new M.R(8);a.Ja&&(a.Ja=null);try{a.T.close&&a.T.close(a)}catch(b){throw b;}finally{M.streams[a.ma]=null}a.ma=null},$(a,b,c){if(null===a.ma)throw new M.R(8);if(!a.seekable||!a.T.$)throw new M.R(70);if(0!=c&&1!=c&&2!=c)throw new M.R(28);
a.position=a.T.$(a,b,c);a.Bb=[];return a.position},read(a,b,c,d,f){if(0>d||0>f)throw new M.R(28);if(null===a.ma)throw new M.R(8);if(1===(a.flags&2097155))throw new M.R(8);if(P(a.node.mode))throw new M.R(31);if(!a.T.read)throw new M.R(28);var g="undefined"!=typeof f;if(!g)f=a.position;else if(!a.seekable)throw new M.R(70);b=a.T.read(a,b,c,d,f);g||(a.position+=b);return b},write(a,b,c,d,f,g){if(0>d||0>f)throw new M.R(28);if(null===a.ma)throw new M.R(8);if(0===(a.flags&2097155))throw new M.R(8);if(P(a.node.mode))throw new M.R(31);
if(!a.T.write)throw new M.R(28);a.seekable&&a.flags&1024&&M.$(a,0,2);var h="undefined"!=typeof f;if(!h)f=a.position;else if(!a.seekable)throw new M.R(70);b=a.T.write(a,b,c,d,f,g);h||(a.position+=b);return b},ra(a,b,c,d,f){if(0!==(d&2)&&0===(f&2)&&2!==(a.flags&2097155))throw new M.R(2);if(1===(a.flags&2097155))throw new M.R(2);if(!a.T.ra)throw new M.R(43);if(!b)throw new M.R(28);return a.T.ra(a,b,c,d,f)},va(a,b,c,d,f){return a.T.va?a.T.va(a,b,c,d,f):0},La(a,b,c){if(!a.T.La)throw new M.R(59);return a.T.La(a,
b,c)},cc(a,b={}){b.flags=b.flags||0;b.encoding=b.encoding||"binary";"utf8"!==b.encoding&&"binary"!==b.encoding&&F(`Invalid encoding type "${b.encoding}"`);var c=M.open(a,b.flags);a=M.stat(a).size;var d=new Uint8Array(a);M.read(c,d,0,a,0);"utf8"===b.encoding&&(d=Pa(d));M.close(c);return d},ic(a,b,c={}){c.flags=c.flags||577;a=M.open(a,c.flags,c.mode);"string"==typeof b&&(b=new Uint8Array(Sa(b)));ArrayBuffer.isView(b)?M.write(a,b,0,b.byteLength,void 0,c.Kb):F("Unsupported data type");M.close(a)},Ba:()=>
M.Xa,Lb(a){a=U(a,{ba:!0});if(null===a.node)throw new M.R(44);if(!P(a.node.mode))throw new M.R(54);var b=S(a.node,"x");if(b)throw new M.R(b);M.Xa=a.path},Ea(a,b,c){M.Ka=!0;a??=e.stdin;b??=e.stdout;c??=e.stderr;a?M.la("/dev","stdin",a):M.oa("/dev/tty","/dev/stdin");b?M.la("/dev","stdout",null,b):M.oa("/dev/tty","/dev/stdout");c?M.la("/dev","stderr",null,c):M.oa("/dev/tty1","/dev/stderr");M.open("/dev/stdin",0);M.open("/dev/stdout",1);M.open("/dev/stderr",1)},bc(){M.Ka=!1;for(var a of M.streams)a&&M.close(a)},
Rb(a,b){try{var c=U(a,{ba:!b});a=c.path}catch(g){}var d=!1,f=null;try{c=U(a,{parent:!0}),L(a),c=U(a,{ba:!b}),d=!0,f=c.node}catch(g){}return d?f:null},la(a,b,c,d){a=Ka("string"==typeof a?a:T(a),b);b=bb(!!c,!!d);var f;(f=M.la).Na??(f.Na=64);f=M.qa(M.la.Na++,0);Va(f,{open(g){g.seekable=!1},close(){d?.buffer?.length&&d(10)},read(g,h,n,r){for(var p=0,l=0;l<r;l++){try{var t=c()}catch(y){throw new M.R(29);}if(void 0===t&&0===p)throw new M.R(6);if(null===t||void 0===t)break;p++;h[n+l]=t}p&&(g.node.ha=Date.now());
return p},write(g,h,n,r){for(var p=0;p<r;p++)try{d(h[n+p])}catch(l){throw new M.R(29);}r&&(g.node.aa=g.node.Z=Date.now());return p}});return wb(a,b,f)}};function Fb(a,b,c){if("/"===b.charAt(0))return b;a=-100===a?M.Ba():V(a).path;if(0==b.length){if(!c)throw new M.R(44);return a}return a+"/"+b}
function Gb(a,b){x[a/4]=b.mb;x[(a+4)/4]=b.mode;C[(a+8)/8]=BigInt(b.yb);x[(a+16)/4]=b.uid;x[(a+20)/4]=b.rb;x[(a+24)/4]=b.ya;A[(a+32)/8]=BigInt(b.size);w[(a+40)/4]=4096;w[(a+44)/4]=b.Va;var c=b.ha.getTime(),d=b.aa.getTime(),f=b.Z.getTime();A[(a+48)/8]=BigInt(Math.floor(c/1E3));C[(a+56)/8]=BigInt(c%1E3*1E6);A[(a+64)/8]=BigInt(Math.floor(d/1E3));C[(a+72)/8]=BigInt(d%1E3*1E6);A[(a+80)/8]=BigInt(Math.floor(f/1E3));C[(a+88)/8]=BigInt(f%1E3*1E6);A[(a+96)/8]=BigInt(b.sb);return 0}
var I=void 0,Hb=0,Ib=[0,31,60,91,121,152,182,213,244,274,305,335],Jb=[0,31,59,90,120,151,181,212,243,273,304,334],Kb={},Lb=a=>{if(a instanceof wa||"unwind"==a)return q;throw a;},Mb=a=>{q=a;Ba||0<Hb||(e.onExit?.(a),ka=!0);throw new wa(a);},Nb=a=>{if(!ka)try{if(a(),!(Ba||0<Hb))try{q=a=q,Mb(a)}catch(b){Lb(b)}}catch(b){Lb(b)}},Ob=[],Pb={},Rb=()=>{if(!Qb){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:(globalThis.navigator?.language??"C").replace("-","_")+".UTF-8",
_:da||"./this.program"},b;for(b in Pb)void 0===Pb[b]?delete a[b]:a[b]=Pb[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);Qb=c}return Qb},Qb;M.Mb=(a,b,c,d,f,g,h,n,r,p)=>{jb(a,b,c,d,f,n,r,p).then(g).catch(h)};M.ac=jb;M.ja=Array(4096);M.X(O,{},"/");Y("/tmp");Y("/home");Y("/home/web_user");
(function(){Y("/dev");Va(M.qa(1,3),{read:()=>0,write:(d,f,g,h)=>h,$:()=>0});wb("/dev/null",M.qa(1,3));Ua(M.qa(5,0),Xa);Ua(M.qa(6,0),Ya);wb("/dev/tty",M.qa(5,0));wb("/dev/tty1",M.qa(6,0));var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(Ma(a),b=a.byteLength);return a[--b]};M.la("/dev","random",c);M.la("/dev","urandom",c);Y("/dev/shm");Y("/dev/shm/tmp")})();
(function(){Y("/proc");var a=Y("/proc/self");Y("/proc/self/fd");M.X({X(){var b=M.createNode(a,"fd",16895,73);b.T={$:O.T.$};b.S={pa(c,d){c=+d;var f=V(c);c={parent:null,X:{bb:"fake"},S:{na:()=>f.path},id:c+1};return c.parent=c},za(){return Array.from(M.streams.entries()).filter(([,c])=>c).map(([c])=>c.toString())}};return b}},{},"/proc/self/fd")})();M.ob={MEMFS:O};e.noExitRuntime&&(Ba=e.noExitRuntime);e.preloadPlugins&&(gb=e.preloadPlugins);e.print&&(ja=e.print);e.printErr&&(k=e.printErr);
e.wasmBinary&&(m=e.wasmBinary);e.arguments&&(ca=e.arguments);e.thisProgram&&(da=e.thisProgram);if(e.preInit)for("function"==typeof e.preInit&&(e.preInit=[e.preInit]);0<e.preInit.length;)e.preInit.shift()();e.callMain=Sb;e.addRunDependency=fb;e.removeRunDependency=eb;e.FS_preloadFile=jb;e.FS_unlink=(...a)=>M.ua(...a);e.FS_createPath=(...a)=>Bb(...a);e.FS_createDevice=(...a)=>M.la(...a);e.FS=M;e.FS_createDataFile=(...a)=>ib(...a);e.FS_createLazyFile=(...a)=>Eb(...a);
var Tb={13443629:()=>"undefined"!==typeof wasmOffsetConverter},Vb,Za,Wb,Xb,ra,Yb={r:function(a,b,c,d){a=G(a);b=G(b);d=G(d);return F(`Assertion failed: ${H(a)}, at: `+[b?H(b):"unknown filename",c,d?H(d):"unknown function"])},a:function(a,b,c){a=G(a);b=G(b);c=G(c);(new Ea(a)).Ea(b,c);Fa=a;Ga++;throw Fa;},u:()=>0,t:function(a,b,c,d){c=G(c);d=G(d);try{if(isNaN(c)||isNaN(d))return-61;if(0!=b)return-138;if(0>c||0>d)return-28;var f=xb(a).size;b=c+d;b>f&&Ab(a,b);return 0}catch(g){if("undefined"==typeof M||
"ErrnoError"!==g.name)throw g;return-g.W}},g:function(a,b,c){I=c=G(c);try{var d=V(a);switch(b){case 0:var f=Ha();if(0>f)break;for(;M.streams[f];)f++;return sb(d,f).ma;case 1:case 2:return 0;case 3:return d.flags;case 4:return f=Ha(),d.flags|=f,0;case 5:return f=J(),na[(f+0)/2]=2,0;case 6:case 7:return 0}return-28}catch(g){if("undefined"==typeof M||"ErrnoError"!==g.name)throw g;return-g.W}},F:function(a,b){b=G(b);try{return Gb(b,xb(a))}catch(c){if("undefined"==typeof M||"ErrnoError"!==c.name)throw c;
return-c.W}},B:function(a,b){b=G(b);try{if(isNaN(b))return-61;Ab(a,b);return 0}catch(c){if("undefined"==typeof M||"ErrnoError"!==c.name)throw c;return-c.W}},k:function(a,b,c){I=c=G(c);try{var d=V(a);switch(b){case 21509:return d.V?0:-59;case 21505:if(!d.V)return-59;if(d.V.ka.tb){a=[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];var f=J();w[f/4]=25856;w[(f+4)/4]=5;w[(f+8)/4]=191;w[(f+12)/4]=35387;for(var g=0;32>g;g++)u[f+g+17]=a[g]||0}return 0;case 21510:case 21511:case 21512:return d.V?
0:-59;case 21506:case 21507:case 21508:if(!d.V)return-59;if(d.V.ka.ub)for(f=J(),a=[],g=0;32>g;g++)a.push(u[f+g+17]);return 0;case 21519:if(!d.V)return-59;f=J();return w[f/4]=0;case 21520:return d.V?-28:-59;case 21537:case 21531:return f=J(),M.La(d,b,f);case 21523:if(!d.V)return-59;d.V.ka.vb&&(g=[24,80],f=J(),na[f/2]=g[0],na[(f+2)/2]=g[1]);return 0;case 21524:return d.V?0:-59;case 21515:return d.V?0:-59;default:return-28}}catch(h){if("undefined"==typeof M||"ErrnoError"!==h.name)throw h;return-h.W}},
D:function(a,b){a=G(a);b=G(b);try{return a=H(a),Gb(b,M.stat(a,!0))}catch(c){if("undefined"==typeof M||"ErrnoError"!==c.name)throw c;return-c.W}},C:function(a,b,c,d){b=G(b);c=G(c);try{b=H(b);var f=d&256;b=Fb(a,b,d&4096);return Gb(c,f?M.stat(b,!0):M.stat(b))}catch(g){if("undefined"==typeof M||"ErrnoError"!==g.name)throw g;return-g.W}},i:function(a,b,c,d){b=G(b);I=d=G(d);try{b=H(b);b=Fb(a,b);var f=d?Ha():0;return M.open(b,c,f).ma}catch(g){if("undefined"==typeof M||"ErrnoError"!==g.name)throw g;return-g.W}},
s:function(a){a=G(a);try{return a=H(a),M.ta(a),0}catch(b){if("undefined"==typeof M||"ErrnoError"!==b.name)throw b;return-b.W}},E:function(a,b){a=G(a);b=G(b);try{return a=H(a),Gb(b,M.stat(a))}catch(c){if("undefined"==typeof M||"ErrnoError"!==c.name)throw c;return-c.W}},h:function(a,b,c){b=G(b);try{b=H(b);b=Fb(a,b);if(c)if(512===c)M.ta(b);else return-28;else M.ua(b);return 0}catch(d){if("undefined"==typeof M||"ErrnoError"!==d.name)throw d;return-d.W}},I:()=>F(""),m:()=>{Ba=!1;Hb=0},p:function(a){return(a=
G(a))?-52:0},x:function(a,b){a=G(a);b=G(b);a=new Date(1E3*a);w[b/4]=a.getSeconds();w[(b+4)/4]=a.getMinutes();w[(b+8)/4]=a.getHours();w[(b+12)/4]=a.getDate();w[(b+16)/4]=a.getMonth();w[(b+20)/4]=a.getFullYear()-1900;w[(b+24)/4]=a.getDay();var c=a.getFullYear();w[(b+28)/4]=(0!==c%4||0===c%100&&0!==c%400?Jb:Ib)[a.getMonth()]+a.getDate()-1|0;A[(b+40)/8]=BigInt(-(60*a.getTimezoneOffset()));c=(new Date(a.getFullYear(),6,1)).getTimezoneOffset();var d=(new Date(a.getFullYear(),0,1)).getTimezoneOffset();w[(b+
32)/4]=(c!=d&&a.getTimezoneOffset()==Math.min(d,c))|0},v:function(a,b,c,d,f,g,h){a=G(a);f=G(f);g=G(g);h=G(h);try{var n=V(d),r=M.ra(n,a,f,b,c),p=r.wa;w[g/4]=r.Ua;C[h/8]=BigInt(p);return 0}catch(l){if("undefined"==typeof M||"ErrnoError"!==l.name)throw l;return-l.W}},w:function(a,b,c,d,f,g){a=G(a);b=G(b);g=G(g);try{var h=V(f);if(c&2){if(!M.isFile(h.node.mode))throw new M.R(43);d&2||M.va(h,v.slice(a,a+b),g,b,d)}}catch(n){if("undefined"==typeof M||"ErrnoError"!==n.name)throw n;return-n.W}},n:(a,b)=>{Kb[a]&&
(clearTimeout(Kb[a].id),delete Kb[a]);if(!b)return 0;var c=setTimeout(()=>{delete Kb[a];Nb(()=>Wb(a,performance.now()))},b);Kb[a]={id:c,ec:b};return 0},j:function(a,b,c,d){a=G(a);b=G(b);c=G(c);d=G(d);var f=(new Date).getFullYear(),g=(new Date(f,0,1)).getTimezoneOffset();f=(new Date(f,6,1)).getTimezoneOffset();C[a/8]=BigInt(60*Math.max(g,f));w[b/4]=Number(g!=f);b=h=>{var n=Math.abs(h);return`UTC${0<=h?"-":"+"}${String(Math.floor(n/60)).padStart(2,"0")}${String(n%60).padStart(2,"0")}`};a=b(g);b=b(f);
f<g?(N(a,v,c,17),N(b,v,d,17)):(N(a,v,d,17),N(b,v,c,17))},H:function(a,b,c){c=G(c);if(!(0<=a&&3>=a))return 28;A[c/8]=BigInt(Math.round(1E6*(0===a?Date.now():performance.now())));return 0},J:function(a,b,c){a=G(a);b=G(b);c=G(c);Ob.length=0;for(var d;d=v[b++];){var f=105!=d;c+=f&&c%8?4:0;Ob.push(112==d?Number(C[c/8]):106==d?A[c/8]:105==d?w[c/4]:oa[c/8]);c+=f?8:4}return Tb[a](...Ob)},G:()=>Date.now(),q:()=>BigInt(17179869184),b:()=>performance.now(),o:function(a){a=G(a);var b=v.length;if(17179869184<
a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(17179869184,65536*Math.ceil(Math.max(a,d)/65536))-ra.buffer.byteLength+65535)/65536|0;try{ra.grow(BigInt(d));qa();var f=1;break a}catch(g){}f=void 0}if(f)return!0}return!1},z:function(a,b){a=G(a);b=G(b);var c=0,d=0,f;for(f of Rb()){var g=b+c;C[(a+d)/8]=BigInt(g);c+=N(f,v,g,Infinity)+1;d+=8}return 0},A:function(a,b){a=G(a);b=G(b);var c=Rb();C[a/8]=BigInt(c.length);a=0;for(var d of c)a+=Ra(d)+1;C[b/8]=BigInt(a);
return 0},c:a=>{q=a;Mb(a)},d:function(a){try{var b=V(a);M.close(b);return 0}catch(c){if("undefined"==typeof M||"ErrnoError"!==c.name)throw c;return c.W}},f:function(a,b,c,d){b=G(b);c=G(c);d=G(d);try{a:{var f=V(a);a=b;for(var g,h=b=0;h<c;h++){var n=Number(C[a/8]),r=Number(C[(a+8)/8]);a+=16;var p=M.read(f,u,n,r,g);if(0>p){var l=-1;break a}b+=p;if(p<r)break;"undefined"!=typeof g&&(g+=p)}l=b}C[d/8]=BigInt(l);return 0}catch(t){if("undefined"==typeof M||"ErrnoError"!==t.name)throw t;return t.W}},y:function(a,
b,c,d){b=G(b);d=G(d);try{if(isNaN(b))return 61;var f=V(a);M.$(f,b,c);A[d/8]=BigInt(f.position);f.Ja&&0===b&&0===c&&(f.Ja=null);return 0}catch(g){if("undefined"==typeof M||"ErrnoError"!==g.name)throw g;return g.W}},e:function(a,b,c,d){b=G(b);c=G(c);d=G(d);try{a:{var f=V(a);a=b;for(var g,h=b=0;h<c;h++){var n=Number(C[a/8]),r=Number(C[(a+8)/8]);a+=16;var p=M.write(f,u,n,r,g);if(0>p){var l=-1;break a}b+=p;if(p<r)break;"undefined"!=typeof g&&(g+=p)}l=b}C[d/8]=BigInt(l);return 0}catch(t){if("undefined"==
typeof M||"ErrnoError"!==t.name)throw t;return t.W}},l:Mb};
function Zb(){var a=Z;a=Object.assign({},a);var b=d=>f=>d(BigInt(f)),c=d=>f=>Number(d(BigInt(f)));a.M=(d=>(f,g,h)=>d(f,BigInt(g?g:0),BigInt(h?h:0)))(a.M);a.N=(d=>(f,g)=>Number(d(BigInt(f),BigInt(g))))(a.N);a.setThrew=b(a.setThrew);a._emscripten_stack_restore=b(a._emscripten_stack_restore);a.P=c(a.P);a.emscripten_stack_get_current=(d=>()=>Number(d()))(a.emscripten_stack_get_current);a.__cxa_decrement_exception_refcount=b(a.__cxa_decrement_exception_refcount);a.__cxa_increment_exception_refcount=b(a.__cxa_increment_exception_refcount);
a.__cxa_get_exception_ptr=c(a.__cxa_get_exception_ptr);return a}function Sb(a=[]){var b=Vb;a.unshift(da);var c=a.length,d=Xb(8*(c+1)),f=d,g;for(g of a){a=C;var h=f/8,n=BigInt,r=g,p=Ra(r)+1,l=Xb(p);N(r,v,l,p);a[h]=n(l);f+=8}C[f/8]=0n;try{var t=b(c,BigInt(d));q=t;Mb(t);return t}catch(y){return Lb(y)}}
function $b(a=ca){function b(){e.calledRun=!0;if(!ka){pa=!0;e.noFSInit||M.Ka||M.Ea();Z.L();M.ab=!1;la?.(e);e.onRuntimeInitialized?.();e.noInitialRun||Sb(a);if(e.postRun)for("function"==typeof e.postRun&&(e.postRun=[e.postRun]);e.postRun.length;){var c=e.postRun.shift();ya.push(c)}xa(ya)}}if(0<R)db=$b;else{if(e.preRun)for("function"==typeof e.preRun&&(e.preRun=[e.preRun]);e.preRun.length;)Aa();xa(za);0<R?db=$b:e.setStatus?(e.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>e.setStatus(""),1);
b()},1)):b()}}var Z;Z=await (async function(){function a(c){Z=c.exports;c=Z=Zb();Vb=e._main=c.M;Za=c.N;Wb=c.O;Xb=c.P;ra=c.K;qa();return Z}var b={a:Yb};if(e.instantiateWasm)return new Promise(c=>{e.instantiateWasm(b,(d,f)=>{c(a(d,f))})});sa??=e.locateFile?e.locateFile("pnnx.wasm",fa):fa+"pnnx.wasm";return a((await va(b)).instance)}());$b();pa?moduleRtn=e:moduleRtn=new Promise((a,b)=>{la=a;ma=b});
;return moduleRtn}})();if(typeof exports==="object"&&typeof module==="object"){module.exports=createPnnxModule;module.exports.default=createPnnxModule}else if(typeof define==="function"&&define["amd"])define([],()=>createPnnxModule);
